Translates proxy domains into ips before creating security groups
[#120239281]

Signed-off-by: Mark DeLillo <mdelillo@pivotal.io>

diff --git a/images/scripts/run b/images/scripts/run
--- a/images/scripts/run
+++ b/images/scripts/run
@@ -167,13 +167,32 @@ EOF
   cf bind-staging-security-group host
 fi
 
+isIP() {
+   echo $1 | grep -q -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"
+}
+
+getIP() {
+  if isIP $1; then
+    echo $1
+  else
+    dig +short $1
+  fi
+}
+
+
 if [[ ! -z $pcfdev_http_proxy ]]; then
   http_proxy_host=$(echo $pcfdev_http_proxy | sed -e's,^.*://,,' | sed -e's/^.*@//' | cut -d ':' -f 1)
+  http_proxy_ip=$(getIP $http_proxy_host)
+  if [[ ${http_proxy_ip} == "" ]]; then
+    echo "Could not resolve HTTP_PROXY: ${http_proxy_host}"
+    exit 1
+  fi
+
   http_proxy_security_group=$(cat <<EOF
     [
      {
        "protocol": "tcp",
-       "destination": "$http_proxy_host",
+       "destination": "$http_proxy_ip",
        "ports": "1-65535"
      }
     ]
@@ -186,11 +205,17 @@ fi
 
 if [[ ! -z $pcfdev_https_proxy ]]; then
   https_proxy_host=$(echo $pcfdev_https_proxy | sed -e's,^.*://,,' | sed -e's/^.*@//' | cut -d ':' -f 1)
+  https_proxy_ip=$(getIP $https_proxy_host)
+  if [[ ${https_proxy_ip} == "" ]]; then
+    echo "Could not resolve HTTPS_PROXY: ${https_proxy_host}"
+    exit 1
+  fi
+
   https_proxy_security_group=$(cat <<EOF
     [
      {
        "protocol": "tcp",
-       "destination": "$https_proxy_host",
+       "destination": "$https_proxy_ip",
        "ports": "1-65535"
      }
     ]
